### ISSUE TITLE
Captchas

### ISSUE THREAD

**Issue by xevaly** [imvast/ThisAPP-MassAccountCreator#3]
post req require an captcha now

**Comment by xtekky** [comment]
oooh, so saad @xevaly

**Comment by xevaly** [comment]
> oooh, so saad @xevaly

You have html marked as a programming language...

**Comment by xevaly** [comment]
![image](https://user-images.githubusercontent.com/93867555/175194128-65290e61-e774-478a-b7b7-b347bcd84358.png)

**Comment by xtekky** [comment]
@xevaly yes, miss dev that uses scripts from github

**Comment by xevaly** [comment]
> @xevaly yes, miss dev that uses scripts from github
> 

Html is not a programming language
